'use client';

import { useState, useEffect, useCallback } from 'react';
import axios from 'axios';
import {
  Leaf, TreePine, Car, PawPrint, Users, CalendarRange, Sprout, Wind, Droplets, RefreshCw,
  type LucideIcon,
} from 'lucide-react';
import {
  BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend,
} from 'recharts';
import PageHeader from '../../components/PageHeader';
import Breadcrumbs from '../../components/Breadcrumbs';
import { useToast } from '../../components/Toaster';
import { useProjectFilter } from '../ProjectFilterContext';

interface FeedBatch {
  _id: string;
  feedBatchId: string;
  supplyDate?: string;
  totalKg?: number;
}

interface OffsetStats {
  animals: number;
  farmers: number;
  activeDays: number;
  totalOffsetValueTons: number;
  fullOffsets: number;
  fractionalRemainderValue: number;
  feedBatches: FeedBatch[];
}

const TEAL = '#2F9E8C';
const PURPLE = '#9A60A8';
const AMBER = '#D99416';

// Approximate EPA GHG Equivalencies Calculator conversion factors — illustrative only.
const TONS_PER_CAR_YEAR = 4.6;
const SEEDLINGS_PER_TON_10YR = 16.5;

function formatMonth(d?: string): string {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { month: 'short', year: '2-digit' });
}

export default function ImpactPage() {
  const { project } = useProjectFilter();
  const { toast } = useToast() ?? {};
  const [stats, setStats] = useState<OffsetStats | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await axios.get<{ success: boolean; data: OffsetStats }>('/api/carbon-offsets');
      if (data.success) setStats(data.data);
    } catch {
      toast?.('Failed to load impact data', 'error');
    } finally {
      setLoading(false);
    }
  }, [toast]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  if (project === 'mm') {
    return (
      <div>
        <Breadcrumbs items={[{ label: 'Environmental Impact', href: '/dashboard/impact' }]} />
        <PageHeader title="Environmental Impact" description="Milky Mist program" />
        <div className="bg-white rounded-2xl border border-gray-100 p-10 text-center text-sm text-gray-500">
          No Milky Mist impact data yet — this view currently only covers the NainarPalayam program.
        </div>
      </div>
    );
  }

  const totalTons = stats?.totalOffsetValueTons || 0;
  const carsOffRoad = totalTons / TONS_PER_CAR_YEAR;
  const treeSeedlings = totalTons * SEEDLINGS_PER_TON_10YR;

  const feedChartData = (stats?.feedBatches || []).map((b) => ({
    name: b.feedBatchId,
    month: formatMonth(b.supplyDate),
    kg: b.totalKg || 0,
  }));

  const offsetBreakdown = stats
    ? [
        { name: 'Full offsets (1 tCO2e each)', value: stats.fullOffsets, color: TEAL },
        { name: 'Fractional offset (tCO2e)', value: Number(stats.fractionalRemainderValue.toFixed(3)), color: PURPLE },
      ]
    : [];

  const heroStats: Array<{ label: string; value: string; icon: LucideIcon; color: string; bg: string }> = stats
    ? [
        { label: 'Farmers Engaged', value: String(stats.farmers), icon: Users, color: 'text-[#2F9E8C]', bg: 'bg-teal-50' },
        { label: 'Cattle Covered', value: String(stats.animals), icon: PawPrint, color: 'text-[#9A60A8]', bg: 'bg-purple-50' },
        { label: 'Days of Active Feeding', value: String(stats.activeDays), icon: CalendarRange, color: 'text-[#D99416]', bg: 'bg-amber-50' },
      ]
    : [];

  return (
    <div>
      <Breadcrumbs items={[{ label: 'Environmental Impact', href: '/dashboard/impact' }]} />
      <PageHeader
        title="Environmental Impact"
        description="How gramCarbon's methane-reducing feed program is helping the planet"
        actions={
          <button onClick={fetchData} className="p-2 rounded-xl border border-gray-200 hover:bg-gray-50 text-gray-500">
            <RefreshCw size={16} />
          </button>
        }
      />

      {/* Hero */}
      <div className="rounded-2xl border border-gray-100 p-8 mb-6 bg-gradient-to-br from-teal-50 via-white to-purple-50 text-center">
        <Leaf size={32} className="mx-auto text-[#2F9E8C] mb-2" />
        <p className="text-4xl font-extrabold text-gray-900 tabular-nums">
          {loading ? '—' : totalTons.toFixed(3)}
          <span className="text-lg font-semibold text-gray-500 ml-2">tCO2e offset</span>
        </p>
        <p className="text-sm text-gray-500 mt-2 max-w-xl mx-auto">
          Total carbon offset generated by supplying methane-reducing feed to tracked cattle across the
          NainarPalayam program.
        </p>
      </div>

      {/* Farmers / cattle / days */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        {heroStats.map((card) => {
          const Icon = card.icon;
          return (
            <div key={card.label} className="bg-white rounded-2xl border border-gray-100 p-4 flex items-center gap-4">
              <div className={`w-11 h-11 rounded-xl flex items-center justify-center flex-shrink-0 ${card.bg}`}>
                <Icon size={22} className={card.color} />
              </div>
              <div>
                <p className="text-lg font-bold text-gray-900 leading-tight">{card.value}</p>
                <p className="text-xs text-gray-500">{card.label}</p>
              </div>
            </div>
          );
        })}
      </div>

      {/* Equivalencies */}
      <h2 className="text-sm font-semibold text-gray-700 mb-3">What that offset is roughly equal to</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-2">
        <div className="bg-white rounded-2xl border border-gray-100 p-5 flex items-center gap-4">
          <div className="w-14 h-14 rounded-xl flex items-center justify-center flex-shrink-0 bg-amber-50">
            <Car size={26} className="text-[#D99416]" />
          </div>
          <div>
            <p className="text-xl font-bold text-gray-900">{loading ? '—' : carsOffRoad.toFixed(2)} cars</p>
            <p className="text-xs text-gray-500">off the road for a year</p>
          </div>
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 p-5 flex items-center gap-4">
          <div className="w-14 h-14 rounded-xl flex items-center justify-center flex-shrink-0 bg-teal-50">
            <TreePine size={26} className="text-[#2F9E8C]" />
          </div>
          <div>
            <p className="text-xl font-bold text-gray-900">{loading ? '—' : Math.round(treeSeedlings)} tree seedlings</p>
            <p className="text-xs text-gray-500">grown for 10 years</p>
          </div>
        </div>
      </div>
      <p className="text-[11px] text-gray-400 mb-8">
        Illustrative estimates based on approximate EPA Greenhouse Gas Equivalencies Calculator factors
        (~4.6 tCO2e/car/year, ~16.5 seedlings/tCO2e over 10 years) — not a precision measurement.
      </p>

      {/* Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-5 gap-4 mb-8">
        <div className="lg:col-span-3 bg-white rounded-2xl border border-gray-100 p-5">
          <h3 className="text-sm font-semibold text-gray-700 mb-1">Feed Supplied Over Time</h3>
          <p className="text-xs text-gray-400 mb-4">Each batch of methane-reducing feed distributed, by supply date</p>
          {feedChartData.length === 0 ? (
            <div className="h-64 flex items-center justify-center text-sm text-gray-400">No feed batch data yet.</div>
          ) : (
            <ResponsiveContainer width="100%" height={260}>
              <BarChart data={feedChartData} margin={{ top: 4, right: 8, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eee" />
                <XAxis dataKey="month" tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={{ stroke: '#e5e7eb' }} tickLine={false} />
                <YAxis tick={{ fontSize: 11, fill: '#9ca3af' }} axisLine={false} tickLine={false} width={40} />
                <Tooltip
                  formatter={(v) => [`${Number(v).toLocaleString('en-IN')} kg`, 'Feed supplied']}
                  contentStyle={{ borderRadius: 12, border: '1px solid #e5e7eb', fontSize: 12 }}
                />
                <Bar dataKey="kg" name="Feed supplied (kg)" fill={TEAL} radius={[4, 4, 0, 0]} maxBarSize={40} />
              </BarChart>
            </ResponsiveContainer>
          )}
        </div>

        <div className="lg:col-span-2 bg-white rounded-2xl border border-gray-100 p-5">
          <h3 className="text-sm font-semibold text-gray-700 mb-1">Offset Composition</h3>
          <p className="text-xs text-gray-400 mb-4">Full vs. fractional tCO2e accumulated</p>
          {!stats || totalTons === 0 ? (
            <div className="h-64 flex items-center justify-center text-sm text-gray-400">No offset data yet.</div>
          ) : (
            <ResponsiveContainer width="100%" height={260}>
              <PieChart>
                <Pie data={offsetBreakdown} dataKey="value" nameKey="name" innerRadius={55} outerRadius={85} paddingAngle={2}>
                  {offsetBreakdown.map((entry) => (
                    <Cell key={entry.name} fill={entry.color} stroke="#fff" strokeWidth={2} />
                  ))}
                </Pie>
                <Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #e5e7eb', fontSize: 12 }} />
                <Legend verticalAlign="bottom" height={36} wrapperStyle={{ fontSize: 11 }} />
              </PieChart>
            </ResponsiveContainer>
          )}
        </div>
      </div>

      {/* Narrative / "pictures" as icon illustrations */}
      <h2 className="text-sm font-semibold text-gray-700 mb-3">How it works</h2>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        {[
          {
            icon: Sprout,
            color: 'text-[#2F9E8C]',
            bg: 'bg-teal-50',
            title: 'Methane-reducing feed',
            body: 'Farmers supply cattle with a formulated feed additive that lowers enteric methane produced during digestion.',
          },
          {
            icon: Wind,
            color: 'text-[#9A60A8]',
            bg: 'bg-purple-50',
            title: 'Fewer emissions per cow-day',
            body: 'Every verified feeding day is converted into a measurable fractional carbon offset using an audited emission-reduction formula.',
          },
          {
            icon: Droplets,
            color: 'text-[#D99416]',
            bg: 'bg-amber-50',
            title: 'Offsets add up',
            body: 'Fractional offsets accumulate into full tCO2e credits — a transparent, farmer-level record of climate impact.',
          },
        ].map((step) => {
          const Icon = step.icon;
          return (
            <div key={step.title} className="bg-white rounded-2xl border border-gray-100 p-5">
              <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-3 ${step.bg}`}>
                <Icon size={24} className={step.color} />
              </div>
              <p className="text-sm font-semibold text-gray-900 mb-1">{step.title}</p>
              <p className="text-xs text-gray-500 leading-relaxed">{step.body}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
