import PDFDocument from 'pdfkit';
import { uploadToS3 } from './s3';
import type { IPurchaseOrder } from './models/PurchaseOrder';

export type DummyDocType = 'QAQC' | 'DN' | 'INVOICE' | 'EWAY_BILL';

const DOC_TITLES: Record<DummyDocType, string> = {
  QAQC: 'QAQC Report',
  DN: 'Goods Receipt Note (GRN)',
  INVOICE: 'Invoice',
  EWAY_BILL: 'E-Way Bill',
};

function renderDummyPdf(order: Pick<IPurchaseOrder, 'poNumber' | 'client' | 'batch' | 'qty'>, docType: DummyDocType): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text(DOC_TITLES[docType], { align: 'center' });
    doc.moveDown(2);
    doc.fontSize(12);
    doc.text(`PO Number: ${order.poNumber}`);
    doc.text(`Client: ${order.client}`);
    if (order.batch) doc.text(`Batch: ${order.batch}`);
    if (order.qty !== undefined) doc.text(`Qty: ${order.qty}`);
    doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`);
    doc.moveDown(4);

    doc.save();
    doc.fontSize(48).fillColor('red').opacity(0.4);
    doc.rotate(-30, { origin: [300, 400] });
    doc.text('DUMMY — FORMAT PENDING', 40, 380, { align: 'center' });
    doc.restore();

    doc.end();
  });
}

const PLACEHOLDER = '—';

function renderEwayBillPdf(order: Pick<IPurchaseOrder, 'poNumber' | 'client' | 'batch' | 'qty'>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const left = 40;
    const right = 555;
    const width = right - left;
    let y = 40;

    // Header
    doc.fontSize(16).font('Helvetica-Bold').text('e-Way Bill', left, y);
    doc.rect(right - 80, y, 80, 80).stroke();
    doc.fontSize(7).font('Helvetica').text('QR CODE', right - 80, y + 36, { width: 80, align: 'center' });
    y += 30;
    doc.moveTo(left, y).lineTo(right, y).stroke();
    y += 10;

    const genDate = new Date();
    const section = (title: string) => {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('black').text(title, left, y);
      y += 14;
      doc.moveTo(left, y).lineTo(right, y).stroke();
      y += 8;
    };

    const field = (label: string, value: string, x: number, colWidth: number) => {
      doc.fontSize(8).font('Helvetica').text(`${label}:`, x, y, { continued: true, width: colWidth });
      doc.font('Helvetica-Bold').text(` ${value}`, { width: colWidth });
    };

    // 1. E-Way Bill Details
    section('1. E-WAY BILL Details');
    const col1 = left, col2 = left + width / 3, col3 = left + (2 * width) / 3;
    field('eWay Bill No', PLACEHOLDER, col1, width / 3 - 10);
    field('Generated Date', genDate.toLocaleString('en-IN'), col2, width / 3 - 10);
    field('Generated By', PLACEHOLDER, col3, width / 3 - 10);
    y += 16;
    field('Mode', PLACEHOLDER, col1, width / 3 - 10);
    field('Approx Distance', PLACEHOLDER, col2, width / 3 - 10);
    field('Valid Upto', PLACEHOLDER, col3, width / 3 - 10);
    y += 16;
    field('Type', PLACEHOLDER, col1, width / 3 - 10);
    field('Document Details', `PO ${order.poNumber}`, col2, width / 3 - 10);
    field('Transaction Type', PLACEHOLDER, col3, width / 3 - 10);
    y += 20;

    // 2. Address Details
    section('2. Address Details');
    const boxW = width / 2 - 10;
    const boxH = 70;
    doc.rect(col1, y, boxW, boxH).stroke();
    doc.rect(col1 + boxW + 20, y, boxW, boxH).stroke();
    doc.fontSize(8).font('Helvetica-Bold').text('From', col1 + 5, y + 5);
    doc.font('Helvetica').text(PLACEHOLDER, col1 + 5, y + 18, { width: boxW - 10 });
    doc.font('Helvetica-Bold').text('To', col1 + boxW + 25, y + 5);
    doc.font('Helvetica').text(order.client, col1 + boxW + 25, y + 18, { width: boxW - 10 });
    y += boxH + 12;

    // 3. Goods Details
    section('3. Goods Details');
    const goodsHeaders = ['HSN Code', 'Product Name & Desc', 'Quantity', 'Taxable Amt', 'Tax Rate'];
    const goodsColW = [70, width - 70 - 60 - 90 - 90, 60, 90, 90];
    let x = col1;
    doc.fontSize(7).font('Helvetica-Bold');
    goodsHeaders.forEach((h, i) => {
      doc.rect(x, y, goodsColW[i], 18).stroke();
      doc.text(h, x + 2, y + 5, { width: goodsColW[i] - 4 });
      x += goodsColW[i];
    });
    y += 18;
    const goodsValues = [
      PLACEHOLDER,
      'CATTLE FEED AND CATTLE FEED',
      order.qty !== undefined ? String(order.qty) : PLACEHOLDER,
      PLACEHOLDER,
      PLACEHOLDER,
    ];
    x = col1;
    doc.font('Helvetica');
    goodsValues.forEach((v, i) => {
      doc.rect(x, y, goodsColW[i], 18).stroke();
      doc.text(v, x + 2, y + 5, { width: goodsColW[i] - 4 });
      x += goodsColW[i];
    });
    y += 26;

    // 4. Transportation Details
    section('4. Transportation Details');
    field('Transporter ID & Name', PLACEHOLDER, col1, width / 2 - 10);
    field('Transporter Doc No & Date', PLACEHOLDER, col1 + width / 2, width / 2 - 10);
    y += 20;

    // 5. Vehicle Details
    section('5. Vehicle Details');
    const vehHeaders = ['Mode', 'Vehicle/Trans Doc No & Dt', 'From', 'Entered Date', 'Entered By'];
    const vehColW = [60, 140, 100, 90, width - 60 - 140 - 100 - 90];
    x = col1;
    doc.fontSize(7).font('Helvetica-Bold');
    vehHeaders.forEach((h, i) => {
      doc.rect(x, y, vehColW[i], 18).stroke();
      doc.text(h, x + 2, y + 5, { width: vehColW[i] - 4 });
      x += vehColW[i];
    });
    y += 18;
    const vehValues = [PLACEHOLDER, PLACEHOLDER, PLACEHOLDER, genDate.toLocaleDateString('en-IN'), PLACEHOLDER];
    x = col1;
    doc.font('Helvetica');
    vehValues.forEach((v, i) => {
      doc.rect(x, y, vehColW[i], 18).stroke();
      doc.text(v, x + 2, y + 5, { width: vehColW[i] - 4 });
      x += vehColW[i];
    });
    y += 40;

    // Barcode placeholder
    doc.rect(left + width / 2 - 90, y, 180, 30).stroke();
    doc.fontSize(7).font('Helvetica').text('BARCODE', left + width / 2 - 90, y + 12, { width: 180, align: 'center' });

    doc.end();
  });
}

function renderGrnPdf(order: Pick<IPurchaseOrder, 'poNumber' | 'client' | 'batch' | 'qty'>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const left = 40;
    const right = 555;
    const width = right - left;
    let y = 40;

    // Header row: title box | page box | company box
    const titleW = 220, pageW = 70, coW = width - titleW - pageW;
    doc.rect(left, y, titleW, 40).stroke();
    doc.rect(left + titleW, y, pageW, 40).stroke();
    doc.rect(left + titleW + pageW, y, coW, 40).stroke();
    doc.fontSize(12).font('Helvetica-Bold').text('GOODS RECEIPT NOTE (GRN)', left + 8, y + 14, { width: titleW - 16 });
    doc.fontSize(7).font('Helvetica').text('Page (sheet)', left + titleW, y + 6, { width: pageW, align: 'center' });
    doc.fontSize(10).font('Helvetica-Bold').text('1 / 1', left + titleW, y + 20, { width: pageW, align: 'center' });
    doc.fontSize(13).font('Helvetica-Bold').text('zeroearth', left + titleW + pageW + 8, y + 6);
    doc.fontSize(7).font('Helvetica').text('ZeroEarth Private Limited', left + titleW + pageW + 8, y + 20);
    doc.text('STPI, Phase 1, Technopark, Thiruvananthapuram, Kerala', left + titleW + pageW + 8, y + 29, { width: coW - 16 });
    y += 40;

    // Delivered To | Date/GRN box
    const dtW = width * 0.65, infoW = width - dtW;
    const dtH = 60;
    doc.rect(left, y, dtW, dtH).stroke();
    doc.rect(left + dtW, y, infoW, dtH / 2).stroke();
    doc.rect(left + dtW, y + dtH / 2, infoW, dtH / 2).stroke();
    doc.fontSize(8).font('Helvetica-Bold').text('DELIVERED TO', left + 5, y + 4);
    doc.font('Helvetica-Bold').text(order.client, left + 5, y + 16);
    doc.font('Helvetica').fontSize(7).text(PLACEHOLDER, left + 5, y + 28, { width: dtW - 10 });
    doc.fontSize(8).font('Helvetica-Bold').text('DATE', left + dtW + 5, y + 4);
    doc.font('Helvetica').text(new Date().toLocaleDateString('en-IN'), left + dtW + 5, y + dtH / 2 - 12);
    doc.font('Helvetica-Bold').text('GRN NO', left + dtW + 5, y + dtH / 2 + 4);
    doc.font('Helvetica').text(PLACEHOLDER, left + dtW + 5, y + dtH - 12);
    y += dtH;

    // Our PO Ref | GRN No row
    doc.rect(left, y, dtW, 16).stroke();
    doc.rect(left + dtW, y, infoW, 16).stroke();
    doc.fontSize(8).font('Helvetica').text(`OUR PO REF: ${order.poNumber}`, left + 5, y + 4);
    doc.text(`GRN NO: ${PLACEHOLDER}`, left + dtW + 5, y + 4);
    y += 16;

    // Project ref row
    doc.rect(left, y, width, 16).stroke();
    doc.font('Helvetica-Bold').text('PROJECT REF', left + 5, y + 4, { continued: true });
    doc.font('Helvetica').text(`  ${PLACEHOLDER}`);
    y += 16;

    // Goods table
    const headers = ['NO', 'QUANTITY KG', 'DESCRIPTION', 'ITEM CODE', 'REMARKS/COMMENTS'];
    const colW = [30, 70, width - 30 - 70 - 90 - 120, 90, 120];
    let x = left;
    doc.fontSize(7).font('Helvetica-Bold');
    headers.forEach((h, i) => {
      doc.rect(x, y, colW[i], 18).stroke();
      doc.text(h, x + 3, y + 5, { width: colW[i] - 6, align: 'center' });
      x += colW[i];
    });
    y += 18;

    const rowH = 100;
    x = left;
    const rowValues = ['1', order.qty !== undefined ? String(order.qty) : PLACEHOLDER, order.batch ?? PLACEHOLDER, PLACEHOLDER, PLACEHOLDER];
    doc.font('Helvetica');
    rowValues.forEach((v, i) => {
      doc.rect(x, y, colW[i], rowH).stroke();
      doc.text(v, x + 3, y + 5, { width: colW[i] - 6 });
      x += colW[i];
    });
    y += rowH;

    // Total row
    doc.rect(left, y, colW[0] + colW[1], 16).stroke();
    doc.rect(left + colW[0] + colW[1], y, width - colW[0] - colW[1], 16).stroke();
    doc.fontSize(8).text(order.qty !== undefined ? `${order.qty} Kg` : PLACEHOLDER, left + colW[0] + 3, y + 4);
    y += 26;

    // Delivered by / Received in good condition
    const halfW = width / 2;
    const footerH = 90;
    doc.rect(left, y, halfW, footerH).stroke();
    doc.rect(left + halfW, y, halfW, footerH).stroke();
    doc.fontSize(8).font('Helvetica-Bold').text('DELIVERED BY', left + 5, y + 4);
    doc.font('Helvetica').fontSize(7).text('ZERO EARTH COMPANY / SKF', left + 5, y + 15);
    doc.fontSize(8).font('Helvetica-Bold').text('Name:', left + 5, y + 32);
    doc.font('Helvetica').fontSize(7).text('ZE- REPRESENTATIVE (SKF)', left + 40, y + 32);
    doc.font('Helvetica').text('Signature', left + 5, y + 65);
    doc.text('Date', left + halfW / 2, y + 65);
    doc.text('Truck Number: ____________', left + 5, y + 78);

    doc.fontSize(8).font('Helvetica-Bold').text('ITEMS RECEIVED IN GOOD CONDITION', left + halfW + 5, y + 4);
    doc.fontSize(8).font('Helvetica-Bold').text('RECEIVED BY', left + halfW + 5, y + 20);
    doc.font('Helvetica').fontSize(7).text(order.client, left + halfW + 5, y + 32);
    doc.text('Signature', left + halfW + 5, y + 65);
    doc.text('Stamp', left + halfW + halfW / 3, y + 65);
    doc.text('Date', left + halfW + (2 * halfW) / 3, y + 65);

    doc.end();
  });
}

function renderInvoicePdf(order: Pick<IPurchaseOrder, 'poNumber' | 'client' | 'batch' | 'qty'>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const left = 40;
    const right = 555;
    const width = right - left;
    let y = 40;

    // Header: company letterhead | TAX INVOICE title
    doc.fontSize(15).font('Helvetica-Bold').text('zeroearth', left, y);
    doc.fontSize(7).font('Helvetica').text('ZeroEarth Private Limited', left, y + 18);
    doc.text('STPI, Phase 1, Technopark, Thiruvananthapuram, Kerala, 695581', left, y + 27);
    doc.text(`GSTIN: ${PLACEHOLDER}`, left, y + 36);
    doc.fontSize(16).font('Helvetica-Bold').text('TAX INVOICE', left, y, { width, align: 'right' });
    y += 50;
    doc.moveTo(left, y).lineTo(right, y).stroke();
    y += 8;

    // Invoice meta row
    const metaColW = width / 3;
    doc.fontSize(8).font('Helvetica-Bold').text('Invoice No:', left, y, { continued: true });
    doc.font('Helvetica').text(` ${PLACEHOLDER}`);
    doc.font('Helvetica-Bold').text('Invoice Date:', left + metaColW, y, { continued: true });
    doc.font('Helvetica').text(` ${new Date().toLocaleDateString('en-IN')}`);
    doc.font('Helvetica-Bold').text('PO Ref:', left + 2 * metaColW, y, { continued: true });
    doc.font('Helvetica').text(` ${order.poNumber}`);
    y += 20;

    // Bill To / Ship To
    const boxW = width / 2 - 10;
    const boxH = 65;
    doc.rect(left, y, boxW, boxH).stroke();
    doc.rect(left + boxW + 20, y, boxW, boxH).stroke();
    doc.fontSize(8).font('Helvetica-Bold').text('Bill To', left + 5, y + 5);
    doc.font('Helvetica').text(order.client, left + 5, y + 17, { width: boxW - 10 });
    doc.text(PLACEHOLDER, left + 5, y + 29, { width: boxW - 10 });
    doc.font('Helvetica-Bold').text('Ship To', left + boxW + 25, y + 5);
    doc.font('Helvetica').text(order.client, left + boxW + 25, y + 17, { width: boxW - 10 });
    doc.text(PLACEHOLDER, left + boxW + 25, y + 29, { width: boxW - 10 });
    y += boxH + 12;

    // Goods table
    const headers = ['#', 'HSN', 'Description', 'Qty', 'Rate', 'CGST', 'SGST', 'IGST', 'Amount'];
    const colW = [20, 45, width - 20 - 45 - 45 - 60 - 55 - 55 - 55 - 75, 45, 60, 55, 55, 55, 75];
    let x = left;
    doc.fontSize(7).font('Helvetica-Bold');
    headers.forEach((h, i) => {
      doc.rect(x, y, colW[i], 18).stroke();
      doc.text(h, x + 2, y + 5, { width: colW[i] - 4, align: 'center' });
      x += colW[i];
    });
    y += 18;

    const rowValues = [
      '1', PLACEHOLDER, 'CATTLE FEED AND CATTLE FEED',
      order.qty !== undefined ? String(order.qty) : PLACEHOLDER,
      PLACEHOLDER, PLACEHOLDER, PLACEHOLDER, PLACEHOLDER, PLACEHOLDER,
    ];
    const dataRowH = 28;
    x = left;
    doc.font('Helvetica');
    rowValues.forEach((v, i) => {
      doc.rect(x, y, colW[i], dataRowH).stroke();
      doc.text(v, x + 2, y + 5, { width: colW[i] - 4, align: i >= 3 ? 'center' : 'left' });
      x += colW[i];
    });
    y += dataRowH;

    // Totals rows
    const totalsLabelW = width - 100;
    const totalRow = (label: string) => {
      doc.rect(left, y, totalsLabelW, 16).stroke();
      doc.rect(left + totalsLabelW, y, 100, 16).stroke();
      doc.fontSize(8).font('Helvetica').text(label, left + 5, y + 4);
      doc.text(PLACEHOLDER, left + totalsLabelW + 5, y + 4, { width: 90, align: 'right' });
      y += 16;
    };
    totalRow('Taxable Amount');
    totalRow('CGST');
    totalRow('SGST');
    totalRow('IGST');
    doc.rect(left, y, totalsLabelW, 18).stroke();
    doc.rect(left + totalsLabelW, y, 100, 18).stroke();
    doc.fontSize(8).font('Helvetica-Bold').text('Total Invoice Amount', left + 5, y + 5);
    doc.text(PLACEHOLDER, left + totalsLabelW + 5, y + 5, { width: 90, align: 'right' });
    y += 30;

    // Bank details
    doc.fontSize(8).font('Helvetica-Bold').text('Bank Details', left, y);
    y += 12;
    doc.font('Helvetica').fontSize(7);
    doc.text(`Bank Name: ${PLACEHOLDER}`, left, y);
    doc.text(`Account No: ${PLACEHOLDER}`, left, y + 10);
    doc.text(`IFSC: ${PLACEHOLDER}`, left, y + 20);
    y += 40;

    // Signature
    doc.fontSize(8).font('Helvetica').text('For ZeroEarth Private Limited', left, y, { width, align: 'right' });
    doc.text('Authorised Signatory', left, y + 30, { width, align: 'right' });

    doc.end();
  });
}

export async function generateDummyDoc(
  order: Pick<IPurchaseOrder, 'poNumber' | 'client' | 'batch' | 'qty'>,
  docType: DummyDocType
): Promise<{ key: string; url: string }> {
  const buffer =
    docType === 'EWAY_BILL' ? await renderEwayBillPdf(order) :
    docType === 'DN' ? await renderGrnPdf(order) :
    docType === 'INVOICE' ? await renderInvoicePdf(order) :
    await renderDummyPdf(order, docType);
  return uploadToS3(buffer, 'application/pdf', 'po-documents');
}
